version: '3'

volumes:
  db-data:
    driver: local
  db-config:
    driver: local

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - db-config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=juwoong
      - MYSQL_PASSWORD=password
    restart: always
